### ISSUE TITLE
First time backup cause to send all the sms right from the very beginning 

### ISSUE THREAD

**Issue by ramesh-lingappan** [simonchius/PowerBackupDroid#6]
Hi, 

When using the application first time there wont be any sync point, the following line set it as 0,
`            mLastUploadSMSTime = mPreferences.getLong(PreferenceHelper.LAST_UPDATED_SMS_TIMESTAMP, 0)
`

this result in all the old sms being sent in the initial sync, So i suggest if no previous sync point is found the use the current time as the initial sync point

**Comment by simonchius** [comment]
Hi Ramesh, 

Thanks for the feedback. Our plan is to give an option set back up start time in View itself. I think that would solve the issue.
